export enum EquipmentId {
  // --WEAPONS--
  // DAGGERS
  RUSTY_DAGGER = "RUSTY_DAGGER",
  CURVED_DAGGER = "CURVED_DAGGER",
  JAGGED_DAGGER = "JAGGED_DAGGER",
  IRON_DAGGER = "IRON_DAGGER",
  STEEL_DAGGER = "STEEL_DAGGER",
  // SWORDS
  SHORT_SWORD = "SHORT_SWORD",
  LONG_SWORD = "LONG_SWORD",
  BROAD_SWORD = "BROAD_SWORD",
  GREAT_SWORD = "GREAT_SWORD",
  WAR_SWORD = "WAR_SWORD",
  // AXES
  HAND_AXE = "HAND_AXE",
  BATTLE_AXE = "BATTLE_AXE",
  WAR_AXE = "WAR_AXE",
  GREAT_AXE = "GREAT_AXE",
  BEARDED_AXE = "BEARDED_AXE",
  // MACES
  BATTLE_HAMMER = "BATTLE_HAMMER",
  SPIKED_STAR = "SPIKED_STAR",
  HEAVY_MACE = "HEAVY_MACE",
  FLANGED_MACE = "FLANGED_MACE",
  WAR_MALLET = "WAR_MALLET",
  // SPEARS
  IRON_SPEAR = "IRON_SPEAR",
  PIKE = "PIKE",
  TRIDENT = "TRIDENT",
  LANCE = "LANCE",
  HALBERD = "HALBERD",
  // --ARMOR--
  // SHIELDS
  WOODEN_SHIELD = "WOODEN_SHIELD",
  ROUND_TARGE = "ROUND_TARGE",
  KITE_SHIELD = "KITE_SHIELD",
  WOODEN_SCUTUM = "WOODEN_SCUTUM",
  BUCKLER = "BUCKLER",
  TARGET_SHIELD = "TARGET_SHIELD",
  METAL_SCUTUM = "METAL_SCUTUM",
  HEATER_SHIELD = "HEATER_SHIELD",
  ROUND_SHIELD = "ROUND_SHIELD",
  BULWARK_SHIELD = "BULWARK_SHIELD",
  // CHESTS
  LIGHT_MAIL = "lightMail",
  LIGHT_GLOVES = "lightGloves",
  LIGHT_BOOTS = "lightBoots",
  LIGHT_HELMET = "lightHelmet",
  HEAVY_MAIL = "heavyMail",
  HEAVY_GLOVES = "heavyGloves",
  HEAVY_BOOTS = "heavyBoots",
  HEAVY_HELMET = "heavyHelmet",
}
