export enum ItemId {
  // HEALTH
  HEALTH_POTION = "HEALTH_POTION",
  BIG_HEALTH_POTION = "BIG_HEALTH_POTION",
  GIANT_HEALTH_POTION = "GIANT_HEALTH_POTION",
  GRAND_HEALTH_POTION = "GRAND_HEALTH_POTION",
  // ENERGY
  ENERGY_POTION = "ENERGY_POTION",
  BIG_ENERGY_POTION = "BIG_ENERGY_POTION",
  GIANT_ENERGY_POTION = "GIANT_ENERGY_POTION",
  GRAND_ENERGY_POTION = "GRAND_ENERGY_POTION",
  // REJUVENATION
  REJUVENATION_POTION = "REJUVENATION_POTION",
  BIG_REJUVENATION_POTION = "BIG_REJUVENATION_POTION",
  GIANT_REJUVENATION_POTION = "GIANT_REJUVENATION_POTION",
  GRAND_REJUVENATION_POTION = "GRAND_REJUVENATION_POTION",
  // STRENGTH
  STRENGTH_POTION = "STRENGTH_POTION",
  BIG_STRENGTH_POTION = "BIG_STRENGTH_POTION",
  GIANT_STRENGTH_POTION = "GIANT_STRENGTH_POTION",
  GRAND_STRENGTH_POTION = "GRAND_STRENGTH_POTION",
  // DEFENSE
  DEFENSE_POTION = "DEFENSE_POTION",
  BIG_DEFENSE_POTION = "BIG_DEFENSE_POTION",
  GIANT_DEFENSE_POTION = "GIANT_DEFENSE_POTION",
  GRAND_DEFENSE_POTION = "GRAND_DEFENSE_POTION",
  // BONUS
  BONUS_HEALTH_POTION = "BONUS_HEALTH_POTION",
  BONUS_ENERGY_POTION = "BONUS_ENERGY_POTION",
  BONUS_STRENGTH_POTION = "BONUS_STRENGTH_POTION",
  BONUS_DEFENSE_POTION = "BONUS_DEFENSE_POTION",
}
