export enum ItemId {
  // HEALTH
  HEALTH_POTION = "HEALTH_POTION",
  BIG_HEALTH_POTION = "BIG_HEALTH_POTION",
  GIANT_HEALTH_POTION = "GIANT_HEALTH_POTION",
  // ENERGY
  ENERGY_POTION = "ENERGY_POTION",
  BIG_ENERGY_POTION = "BIG_ENERGY_POTION",
  GIANT_ENERGY_POTION = "GIANT_ENERGY_POTION",
  // STRENGTH
  STRENGTH_POTION = "STRENGTH_POTION",
  BIG_STRENGTH_POTION = "BIG_STRENGTH_POTION",
  GIANT_STRENGTH_POTION = "GIANT_STRENGTH_POTION",
  // DEFENSE
  DEFENSE_POTION = "DEFENSE_POTION",
  BIG_DEFENSE_POTION = "BIG_DEFENSE_POTION",
  GIANT_DEFENSE_POTION = "GIANT_DEFENSE_POTION",
}
