export enum Label {
  COLOSSEUM_CHAMPIONS = "colosseumChampions",
  TUTORIAL = "tutorial",
  QUEST_FOR_GLORY = "questForGlory",
  OPTIONS = "options",
  HEALTH = "health",
  STAMINA = "stamina",
  EXPERIENCE = "experience",
  STRENGTH = "strength",
  DEFENSE = "defense",
  GOLD = "gold",
  CONTINUE = "continue",
  LEVEL = "level",
  NEW_GAME = "newGame",
  LOAD_GAME = "loadGame",
  POINTS = "points",
}
