export enum Label {
  HEALTH = "health",
  STAMINA = "stamina",
  EXPERIENCE = "experience",
  STRENGTH = "strength",
  DEFENSE = "defense",
  GOLD = "gold",
  FIGHT = "fight",
  CONTINUE = "continue",
  LEVEL = "level",
  NEW_GAME = "newGame",
  LOAD_GAME = "loadGame",
  POINTS = "points",
  CODEX = "codex",
  ARMORY = "armory",
  ITEMS = "items",
}
