export enum PerkId {
  LAST_STAND = "LAST_STAND",
  BERSERKERS_FURY = "BERSERKERS_FURY",
  IRON_CONSTITUTION = "IRON_CONSTITUTION",
  STEADY_RESOLVE = "STEADY_RESOLVE",
  ANCIENT_STRENGTH = "ANCIENT_STRENGTH",
  ENDLESS_RESERVES = "ENDLESS_RESERVES",
  SHIELD_WALL = "SHIELD_WALL",
  STEADFAST = "STEADFAST",
  BULWARK = "BULWARK",
  RELENTLESS = "RELENTLESS",
  VITAL_FORCE = "VITAL_FORCE",
  BRUTALITY = "BRUTALITY",
}
