export enum StatKey {
  LEVEL = "level",
  HEALTH = "health",
  MAX_HEALTH = "maxHealth",
  STAMINA = "stamina",
  MAX_STAMINA = "maxStamina",
  RAGE = "rage",
  MAX_RAGE = "maxRage",
  STRENGTH = "strength",
  MAX_STRENGTH = "maxStrength",
  DEXTERITY = "dexterity",
  MAX_DEXTERITY = "maxDexterity",
  DEFENSE = "defense",
  MAX_DEFENSE = "maxDefense",
  EXPERIENCE = "experience",
  MAX_EXPERIENCE = "maxExperience",
  POINTS = "points",
  GOLD = "gold",
}
