import type { Ability } from "@/types";
import { AbilityId, BonusStatus } from "@/enums";
import {
  mendWounds,
  piercingThrust,
  reapersEdge,
  tripleRend,
  powerSurge,
  guardiansBoon,
  weakenResolve,
  drainEnergy,
  crushArmor,
  pillage,
  nullify,
  disempower,
} from "@/assets";

export const ABILITIES: Record<AbilityId, Ability> = {
  [AbilityId.TRIPLE_REND]: {
    id: AbilityId.TRIPLE_REND,
    label: "Triple Rend",
    description: "Deals 300% damage",
    image: tripleRend,
    energy: 10,
    cooldown: 0,
    maxCooldown: 2,
    points: 5,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.PIERCING_THRUST]: {
    id: AbilityId.PIERCING_THRUST,
    label: "Piercing Thrust",
    description: "Deals damage that ignores armor",
    image: piercingThrust,
    energy: 20,
    cooldown: 0,
    maxCooldown: 3,
    points: 10,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.REAPERS_EDGE]: {
    id: AbilityId.REAPERS_EDGE,
    label: "Reaper's Edge",
    description: "Deals damage based on missing HP",
    image: reapersEdge,
    energy: 30,
    cooldown: 0,
    maxCooldown: 4,
    points: 15,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.MEND_WOUNDS]: {
    id: AbilityId.MEND_WOUNDS,
    label: "Mend Wounds",
    description: "Restores a random % of HP",
    image: mendWounds,
    energy: 40,
    cooldown: 0,
    maxCooldown: 5,
    points: 20,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.POWER_SURGE]: {
    id: AbilityId.POWER_SURGE,
    label: "Power Surge",
    description: "Restores a random % of STR",
    image: powerSurge,
    energy: 50,
    cooldown: 0,
    maxCooldown: 6,
    points: 25,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.GUARDIANS_BOON]: {
    id: AbilityId.GUARDIANS_BOON,
    label: "Guardian's Boon",
    description: "Restores a random % of DEF",
    image: guardiansBoon,
    energy: 60,
    cooldown: 0,
    maxCooldown: 7,
    points: 30,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.DRAIN_ENERGY]: {
    id: AbilityId.DRAIN_ENERGY,
    label: "Drain Energy",
    description: "Drains a random % of EP",
    image: drainEnergy,
    energy: 70,
    cooldown: 0,
    maxCooldown: 8,
    points: 35,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.WEAKEN_RESOLVE]: {
    id: AbilityId.WEAKEN_RESOLVE,
    label: "Weaken Resolve",
    description: "Drains a random % of STR",
    image: weakenResolve,
    energy: 80,
    cooldown: 0,
    maxCooldown: 9,
    points: 40,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.CRUSH_ARMOR]: {
    id: AbilityId.CRUSH_ARMOR,
    label: "Crush Armor",
    description: "Drains a random % of DEF",
    image: crushArmor,
    energy: 90,
    cooldown: 0,
    maxCooldown: 10,
    points: 45,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.PILLAGE]: {
    id: AbilityId.PILLAGE,
    label: "Pillage",
    description: "Removes a random piece of equipment",
    image: pillage,
    energy: 100,
    cooldown: 0,
    maxCooldown: 1,
    points: 50,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.NULLIFY]: {
    id: AbilityId.NULLIFY,
    label: "Nullify",
    description: "Removes a random perk",
    image: nullify,
    energy: 110,
    cooldown: 0,
    maxCooldown: 12,
    points: 55,
    status: BonusStatus.LOCKED,
  },
  [AbilityId.DISEMPOWER]: {
    id: AbilityId.DISEMPOWER,
    label: "Disempower",
    description: "Removes a random ability",
    image: disempower,
    energy: 120,
    cooldown: 0,
    maxCooldown: 13,
    points: 60,
    status: BonusStatus.LOCKED,
  },
};
