import { EquipmentId, EquipmentSlot, BonusStatus } from "@/enums";
import type { Equipment } from "@/types";
import {
  weapon01,
  weapon02,
  weapon03,
  weapon04,
  weapon05,
  weapon06,
  weapon07,
  weapon08,
  weapon09,
  weapon10,
  weapon11,
  weapon12,
  shield01,
  shield02,
  shield03,
  shield04,
  shield05,
  shield06,
  shield07,
  shield08,
  shield09,
  shield10,
  shield11,
  shield12,
  breastplate01,
  breastplate02,
  breastplate03,
  breastplate04,
  breastplate05,
  breastplate06,
  breastplate07,
  breastplate08,
  breastplate09,
  breastplate10,
  breastplate11,
  breastplate12,
  gauntlets01,
  gauntlets02,
  gauntlets03,
  gauntlets04,
  gauntlets05,
  gauntlets06,
  gauntlets07,
  gauntlets08,
  gauntlets09,
  gauntlets10,
  gauntlets11,
  gauntlets12,
  helmet01,
  helmet02,
  helmet03,
  helmet04,
  helmet05,
  helmet06,
  helmet07,
  helmet08,
  helmet09,
  helmet10,
  helmet11,
  helmet12,
  boots01,
  boots02,
  boots03,
  boots04,
  boots05,
  boots06,
  boots07,
  boots08,
  boots09,
  boots10,
  boots11,
  boots12,
} from "@/assets";

export const EQUIPMENT: Record<EquipmentId, Equipment> = {
  // WEAPONS

  [EquipmentId.SHORT_SWORD]: {
    label: "Short Sword",
    image: weapon01,
    description: "DMG: 1 - 5",
    gold: 100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [1, 5],
  },
  [EquipmentId.LONG_SWORD]: {
    label: "Long Sword",
    image: weapon02,
    description: "DMG: 5 - 10",
    gold: 200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [5, 10],
  },
  [EquipmentId.GREAT_SWORD]: {
    label: "Great Sword",
    image: weapon03,
    description: "DMG: 10 - 15",
    gold: 300,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [10, 15],
  },
  [EquipmentId.BATTLE_AXE]: {
    label: "Battle Axe",
    image: weapon04,
    description: "DMG: 20 - 25",
    gold: 400,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [20, 25],
  },
  [EquipmentId.LABRYS]: {
    label: "Labrys",
    image: weapon05,
    description: "DMG: 25 - 30",
    gold: 500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [25, 30],
  },
  [EquipmentId.BARDICHE]: {
    label: "Bardiche",
    image: weapon06,
    description: "DMG: 30 - 35",
    gold: 600,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [30, 35],
  },
  [EquipmentId.WAR_HAMMER]: {
    label: "War Hammer",
    image: weapon07,
    description: "DMG: 35 - 40",
    gold: 700,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [35, 40],
  },
  [EquipmentId.MORNING_STAR]: {
    label: "Morning Star",
    image: weapon08,
    description: "DMG: 40 - 45",
    gold: 800,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [40, 45],
  },
  [EquipmentId.FLANGED_MACE]: {
    label: "Flanged Mace",
    image: weapon09,
    description: "DMG: 50 - 55",
    gold: 900,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [50, 55],
  },
  [EquipmentId.PIKE]: {
    label: "Pike",
    image: weapon10,
    description: "DMG: 55 - 60",
    gold: 1000,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [55, 60],
  },
  [EquipmentId.TRIDENT]: {
    label: "Trident",
    image: weapon11,
    description: "DMG: 60 - 65",
    gold: 1100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [60, 65],
  },
  [EquipmentId.LANCE]: {
    label: "Lance",
    image: weapon12,
    description: "DMG: 65 - 70",
    gold: 1200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [65, 70],
  },
  // SHIELDS
  [EquipmentId.LEATHER_SHIELD]: {
    label: "Leather Shield",
    image: shield01,
    description: "ARMOR: 2",
    gold: 100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 2,
  },
  [EquipmentId.REINFORCED_SHIELD]: {
    label: "Reinforced Shield",
    image: shield02,
    description: "ARMOR: 4",
    gold: 200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 4,
  },
  [EquipmentId.EASTERN_SHIELD]: {
    label: "Eastern Shield",
    image: shield03,
    description: "ARMOR: 6",
    gold: 300,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 6,
  },
  [EquipmentId.IRON_SHIELD]: {
    label: "Iron Shield",
    image: shield04,
    description: "ARMOR: 8",
    gold: 400,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 8,
  },
  [EquipmentId.SCALE_SHIELD]: {
    label: "Scale Shield",
    image: shield05,
    description: "ARMOR: 10",
    gold: 500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 10,
  },
  [EquipmentId.STEEL_SHIELD]: {
    label: "Steel Shield",
    image: shield06,
    description: "ARMOR: 12",
    gold: 600,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 12,
  },
  [EquipmentId.PLATE_SHIELD]: {
    label: "Plate Shield",
    image: shield07,
    description: "ARMOR: 14",
    gold: 700,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 14,
  },
  [EquipmentId.KNIGHT_SHIELD]: {
    label: "Knight Shield",
    image: shield08,
    description: "ARMOR: 16",
    gold: 800,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 16,
  },
  [EquipmentId.ELITE_SHIELD]: {
    label: "Elite Shield",
    image: shield09,
    description: "ARMOR: 18",
    gold: 900,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 18,
  },
  [EquipmentId.DRAGON_SHIELD]: {
    label: "Dragon Shield",
    image: shield10,
    description: "ARMOR: 20",
    gold: 1000,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 20,
  },
  [EquipmentId.SKULL_SHIELD]: {
    label: "Skull Shield",
    image: shield11,
    description: "ARMOR: 22",
    gold: 1100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 22,
  },
  [EquipmentId.DEATH_SHIELD]: {
    label: "Death Shield",
    image: shield12,
    description: "ARMOR: 24",
    gold: 1200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 24,
  },
  // BREASTPLATES
  [EquipmentId.LEATHER_BREASTPLATE]: {
    label: "Leather Breastplate",
    image: breastplate01,
    description: "ARMOR: 2",
    gold: 100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 2,
  },
  [EquipmentId.REINFORCED_BREASTPLATE]: {
    label: "Reinforced Breastplate",
    image: breastplate02,
    description: "ARMOR: 4",
    gold: 200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 4,
  },
  [EquipmentId.EASTERN_BREASTPLATE]: {
    label: "Eastern Breastplate",
    image: breastplate03,
    description: "ARMOR: 6",
    gold: 300,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 6,
  },
  [EquipmentId.IRON_BREASTPLATE]: {
    label: "Iron Breastplate",
    image: breastplate04,
    description: "ARMOR: 8",
    gold: 400,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 8,
  },
  [EquipmentId.SCALE_BREASTPLATE]: {
    label: "Scale Breastplate",
    image: breastplate05,
    description: "ARMOR: 10",
    gold: 500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 10,
  },
  [EquipmentId.STEEL_BREASTPLATE]: {
    label: "Steel Breastplate",
    image: breastplate06,
    description: "ARMOR: 12",
    gold: 600,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 12,
  },
  [EquipmentId.PLATE_BREASTPLATE]: {
    label: "Plate Breastplate",
    image: breastplate07,
    description: "ARMOR: 14",
    gold: 700,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 14,
  },
  [EquipmentId.KNIGHT_BREASTPLATE]: {
    label: "Knight Breastplate",
    image: breastplate08,
    description: "ARMOR: 16",
    gold: 800,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 16,
  },
  [EquipmentId.ELITE_BREASTPLATE]: {
    label: "Elite Breastplate",
    image: breastplate09,
    description: "ARMOR: 18",
    gold: 900,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 18,
  },
  [EquipmentId.DRAGON_BREASTPLATE]: {
    label: "Dragon Breastplate",
    image: breastplate10,
    description: "ARMOR: 20",
    gold: 1000,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 20,
  },
  [EquipmentId.SKULL_BREASTPLATE]: {
    label: "Skull Breastplate",
    image: breastplate11,
    description: "ARMOR: 22",
    gold: 1100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 22,
  },
  [EquipmentId.DEATH_BREASTPLATE]: {
    label: "Death Breastplate",
    image: breastplate12,
    description: "ARMOR: 24",
    gold: 1200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BREASTPLATE,
    armor: 24,
  },
  // GAUNTLETS
  [EquipmentId.LEATHER_GAUNTLETS]: {
    label: "Leather Gauntlets",
    image: gauntlets01,
    description: "ARMOR: 2",
    gold: 100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 2,
  },
  [EquipmentId.REINFORCED_GAUNTLETS]: {
    label: "Reinforced Gauntlets",
    image: gauntlets02,
    description: "ARMOR: 4",
    gold: 200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 4,
  },
  [EquipmentId.EASTERN_GAUNTLETS]: {
    label: "Eastern Gauntlets",
    image: gauntlets03,
    description: "ARMOR: 6",
    gold: 300,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 6,
  },
  [EquipmentId.IRON_GAUNTLETS]: {
    label: "Iron Gauntlets",
    image: gauntlets04,
    description: "ARMOR: 8",
    gold: 400,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 8,
  },
  [EquipmentId.SCALE_GAUNTLETS]: {
    label: "Scale Gauntlets",
    image: gauntlets05,
    description: "ARMOR: 10",
    gold: 500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 10,
  },
  [EquipmentId.STEEL_GAUNTLETS]: {
    label: "Steel Gauntlets",
    image: gauntlets06,
    description: "ARMOR: 12",
    gold: 600,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 12,
  },
  [EquipmentId.PLATE_GAUNTLETS]: {
    label: "Plate Gauntlets",
    image: gauntlets07,
    description: "ARMOR: 14",
    gold: 700,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 14,
  },
  [EquipmentId.KNIGHT_GAUNTLETS]: {
    label: "Knight Gauntlets",
    image: gauntlets08,
    description: "ARMOR: 16",
    gold: 800,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 16,
  },
  [EquipmentId.ELITE_GAUNTLETS]: {
    label: "Elite Gauntlets",
    image: gauntlets09,
    description: "ARMOR: 18",
    gold: 900,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 18,
  },
  [EquipmentId.DRAGON_GAUNTLETS]: {
    label: "Dragon Gauntlets",
    image: gauntlets10,
    description: "ARMOR: 20",
    gold: 1000,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 20,
  },
  [EquipmentId.SKULL_GAUNTLETS]: {
    label: "Skull Gauntlets",
    image: gauntlets11,
    description: "ARMOR: 22",
    gold: 1100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 22,
  },
  [EquipmentId.DEATH_GAUNTLETS]: {
    label: "Death Gauntlets",
    image: gauntlets12,
    description: "ARMOR: 24",
    gold: 1200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GAUNTLETS,
    armor: 24,
  },
  // BOOTS
  [EquipmentId.LEATHER_BOOTS]: {
    label: "Leather Boots",
    image: boots01,
    description: "ARMOR: 2",
    gold: 100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 2,
  },
  [EquipmentId.REINFORCED_BOOTS]: {
    label: "Reinforced Boots",
    image: boots02,
    description: "ARMOR: 4",
    gold: 200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 4,
  },
  [EquipmentId.EASTERN_BOOTS]: {
    label: "Eastern Boots",
    image: boots03,
    description: "ARMOR: 6",
    gold: 300,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 6,
  },
  [EquipmentId.IRON_BOOTS]: {
    label: "Iron Boots",
    image: boots04,
    description: "ARMOR: 8",
    gold: 400,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 8,
  },
  [EquipmentId.SCALE_BOOTS]: {
    label: "Scale Boots",
    image: boots05,
    description: "ARMOR: 10",
    gold: 500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 10,
  },
  [EquipmentId.STEEL_BOOTS]: {
    label: "Steel Boots",
    image: boots06,
    description: "ARMOR: 12",
    gold: 600,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 12,
  },
  [EquipmentId.PLATE_BOOTS]: {
    label: "Plate Boots",
    image: boots07,
    description: "ARMOR: 14",
    gold: 700,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 14,
  },
  [EquipmentId.KNIGHT_BOOTS]: {
    label: "Knight Boots",
    image: boots08,
    description: "ARMOR: 16",
    gold: 800,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 16,
  },
  [EquipmentId.ELITE_BOOTS]: {
    label: "Elite Boots",
    image: boots09,
    description: "ARMOR: 18",
    gold: 900,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 18,
  },
  [EquipmentId.DRAGON_BOOTS]: {
    label: "Dragon Boots",
    image: boots10,
    description: "ARMOR: 20",
    gold: 1000,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 20,
  },
  [EquipmentId.SKULL_BOOTS]: {
    label: "Skull Boots",
    image: boots11,
    description: "ARMOR: 22",
    gold: 1100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 22,
  },
  [EquipmentId.DEATH_BOOTS]: {
    label: "Death Boots",
    image: boots12,
    description: "ARMOR: 24",
    gold: 1200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 24,
  },
  // HELMETS
  [EquipmentId.LEATHER_HELMET]: {
    label: "Leather Helmet",
    image: helmet01,
    description: "ARMOR: 2",
    gold: 100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 2,
  },
  [EquipmentId.REINFORCED_HELMET]: {
    label: "Reinforced Helmet",
    image: helmet02,
    description: "ARMOR: 4",
    gold: 200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 4,
  },
  [EquipmentId.EASTERN_HELMET]: {
    label: "Eastern Helmet",
    image: helmet03,
    description: "ARMOR: 6",
    gold: 300,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 6,
  },
  [EquipmentId.IRON_HELMET]: {
    label: "Iron Helmet",
    image: helmet04,
    description: "ARMOR: 8",
    gold: 400,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 8,
  },
  [EquipmentId.SCALE_HELMET]: {
    label: "Scale Helmet",
    image: helmet05,
    description: "ARMOR: 10",
    gold: 500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 10,
  },
  [EquipmentId.STEEL_HELMET]: {
    label: "Steel Helmet",
    image: helmet06,
    description: "ARMOR: 12",
    gold: 600,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 12,
  },
  [EquipmentId.PLATE_HELMET]: {
    label: "Plate Helmet",
    image: helmet07,
    description: "ARMOR: 14",
    gold: 700,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 14,
  },
  [EquipmentId.KNIGHT_HELMET]: {
    label: "Knight Helmet",
    image: helmet08,
    description: "ARMOR: 16",
    gold: 800,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 16,
  },
  [EquipmentId.ELITE_HELMET]: {
    label: "Elite Helmet",
    image: helmet09,
    description: "ARMOR: 18",
    gold: 900,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 18,
  },
  [EquipmentId.DRAGON_HELMET]: {
    label: "Dragon Helmet",
    image: helmet10,
    description: "ARMOR: 20",
    gold: 1000,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 20,
  },
  [EquipmentId.SKULL_HELMET]: {
    label: "Skull Helmet",
    image: helmet11,
    description: "ARMOR: 22",
    gold: 1100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 22,
  },
  [EquipmentId.DEATH_HELMET]: {
    label: "Death Helmet",
    image: helmet12,
    description: "ARMOR: 24",
    gold: 1200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 24,
  },
};
