import {
  StatKey,
  EquipmentId,
  EquipmentSlot,
  Operator,
  BonusStatus,
} from "@/enums";
import type { Equipment } from "@/types";
import {
  dagger1,
  dagger2,
  dagger3,
  dagger4,
  dagger5,
  sword1,
  sword2,
  sword3,
  sword4,
  sword5,
  axe1,
  axe2,
  axe3,
  axe4,
  axe5,
  mace1,
  mace2,
  mace3,
  mace4,
  mace5,
  spear1,
  spear2,
  spear3,
  spear4,
  spear5,
  shield1,
  shield2,
  shield3,
  shield4,
  shield5,
  shield6,
  shield7,
  shield8,
  shield9,
  shield10,
} from "@/assets";

export const EQUIPMENT: Record<EquipmentId, Equipment> = {
  // --WEAPONS--
  // DAGGERS
  [EquipmentId.RUSTY_DAGGER]: {
    label: "Rusty Dagger",
    image: dagger1,
    description: "DMG: 1 - 3",
    gold: 10,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [1, 3],
  },
  [EquipmentId.CURVED_DAGGER]: {
    label: "Curved Dagger",
    image: dagger2,
    description: "DMG: 3 - 5",
    gold: 20,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [3, 5],
  },
  [EquipmentId.JAGGED_DAGGER]: {
    label: "Jagged Dagger",
    image: dagger3,
    description: "DMG: 5 - 7",
    gold: 30,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [5, 7],
  },
  [EquipmentId.IRON_DAGGER]: {
    label: "Iron Dagger",
    image: dagger4,
    description: "DMG: 7 - 9",
    gold: 40,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [7, 9],
  },
  [EquipmentId.STEEL_DAGGER]: {
    label: "Steel Dagger",
    image: dagger5,
    description: "DMG: 9 - 11",
    gold: 50,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [9, 11],
  },
  // SWORDS,
  [EquipmentId.SHORT_SWORD]: {
    label: "Short Sword",
    image: sword1,
    description: "DMG: 8 - 12",
    gold: 60,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [8, 12],
  },
  [EquipmentId.LONG_SWORD]: {
    label: "Long Sword",
    image: sword2,
    description: "DMG: 12 - 16",
    gold: 70,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [12, 16],
  },
  [EquipmentId.BROAD_SWORD]: {
    label: "Broad Sword",
    image: sword3,
    description: "DMG: 16 - 20",
    gold: 80,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [16, 20],
  },
  [EquipmentId.GREAT_SWORD]: {
    label: "Great Sword",
    image: sword4,
    description: "DMG: 20 - 24",
    gold: 90,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [20, 24],
  },
  [EquipmentId.WAR_SWORD]: {
    label: "War Sword",
    image: sword5,
    description: "DMG: 24 - 28",
    gold: 100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [24, 28],
  },
  // AXES
  [EquipmentId.HAND_AXE]: {
    label: "Hand Axe",
    image: axe1,
    description: "DMG: 30",
    gold: 120,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [30, 30],
  },
  [EquipmentId.BATTLE_AXE]: {
    label: "Battle Axe",
    image: axe2,
    description: "DMG: 33",
    gold: 140,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [33, 33],
  },
  [EquipmentId.WAR_AXE]: {
    label: "War Axe",
    image: axe3,
    description: "DMG: 36",
    gold: 160,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [36, 36],
  },
  [EquipmentId.GREAT_AXE]: {
    label: "Great Axe",
    image: axe4,
    description: "DMG: 39",
    gold: 180,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [39, 39],
  },
  [EquipmentId.BEARDED_AXE]: {
    label: "Bearded Axe",
    image: axe5,
    description: "DMG: 42",
    gold: 200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [42, 42],
  },
  // MACES
  [EquipmentId.BATTLE_HAMMER]: {
    label: "Battle Hammer",
    image: mace1,
    description: "DMG: 45 - 50",
    gold: 300,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [45, 50],
  },
  [EquipmentId.SPIKED_STAR]: {
    label: "Spiked Star",
    image: mace2,
    description: "DMG: 50 - 55",
    gold: 400,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [50, 55],
  },
  [EquipmentId.HEAVY_MACE]: {
    label: "Heavy Mace",
    image: mace3,
    description: "DMG: 55 - 60",
    gold: 500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [55, 60],
  },
  [EquipmentId.FLANGED_MACE]: {
    label: "Flanged Mace",
    image: mace4,
    description: "DMG: 60 - 65",
    gold: 600,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [60, 65],
  },
  [EquipmentId.WAR_MALLET]: {
    label: "War Mallet",
    image: mace5,
    description: "DMG: 65 - 70",
    gold: 700,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [65, 70],
  },
  // SPEARS
  [EquipmentId.IRON_SPEAR]: {
    label: "Iron Spear",
    image: spear1,
    description: "DMG: 40 - 80",
    gold: 1000,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [40, 80],
  },
  [EquipmentId.PIKE]: {
    label: "Pike",
    image: spear2,
    description: "DMG: 45 - 90",
    gold: 1500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [45, 90],
  },
  [EquipmentId.TRIDENT]: {
    label: "Trident",
    image: spear3,
    description: "DMG: 50 - 100",
    gold: 2000,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [50, 100],
  },
  [EquipmentId.LANCE]: {
    label: "Lance",
    image: spear4,
    description: "DMG: 55 - 110",
    gold: 2500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [55, 110],
  },
  [EquipmentId.HALBERD]: {
    label: "Halberd",
    image: spear5,
    description: "DMG: 60 - 120",
    gold: 3000,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.WEAPON,
    attack: [60, 120],
  },
  // SHIELDS
  [EquipmentId.WOODEN_SHIELD]: {
    label: "Wooden Shield",
    image: shield1,
    description: "ARMOR: 2",
    gold: 50,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 2,
  },
  [EquipmentId.ROUND_TARGE]: {
    label: "Round Targe",
    image: shield2,
    description: "ARMOR: 4",
    gold: 100,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 4,
  },
  [EquipmentId.KITE_SHIELD]: {
    label: "Kite Shield",
    image: shield3,
    description: "ARMOR: 6",
    gold: 150,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 6,
  },
  [EquipmentId.WOODEN_SCUTUM]: {
    label: "Wooden Scutum",
    image: shield4,
    description: "ARMOR: 8",
    gold: 200,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 8,
  },
  [EquipmentId.BUCKLER]: {
    label: "Buckler",
    image: shield5,
    description: "ARMOR: 10",
    gold: 250,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 10,
  },
  [EquipmentId.TARGET_SHIELD]: {
    label: "Target Shield",
    image: shield6,
    description: "ARMOR: 12",
    gold: 300,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 12,
  },
  [EquipmentId.METAL_SCUTUM]: {
    label: "Metal Scutum",
    image: shield7,
    description: "ARMOR: 14",
    gold: 350,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 14,
  },
  [EquipmentId.HEATER_SHIELD]: {
    label: "Heater Shield",
    image: shield8,
    description: "ARMOR: 16",
    gold: 400,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 16,
  },
  [EquipmentId.ROUND_SHIELD]: {
    label: "Round Shield",
    image: shield9,
    description: "ARMOR: 18",
    gold: 450,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 18,
  },
  [EquipmentId.BULWARK_SHIELD]: {
    label: "Bulwark Shield",
    image: shield10,
    description: "ARMOR: 20",
    gold: 500,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.SHIELD,
    armor: 20,
  },
  // CHESTS
  [EquipmentId.LIGHT_MAIL]: {
    label: "Light Mail",
    image: "",
    description: "DEF + 10",
    gold: 25,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.CHEST,
    armor: 10,
  },
  [EquipmentId.LIGHT_GLOVES]: {
    label: "Light Gloves",
    image: "",
    description: "DEF + 10",
    gold: 30,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GLOVES,
    armor: 10,
  },
  [EquipmentId.LIGHT_BOOTS]: {
    label: "Light Boots",
    image: "",
    description: "DEF + 10",
    gold: 35,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 10,
  },
  [EquipmentId.LIGHT_HELMET]: {
    label: "Light Helmet",
    image: "",
    description: "DEF + 10",
    gold: 40,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 10,
  },
  [EquipmentId.HEAVY_MAIL]: {
    label: "Heavy Mail",
    image: "",
    description: "DEF + 20",
    gold: 45,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.CHEST,
    armor: 20,
  },
  [EquipmentId.HEAVY_GLOVES]: {
    label: "Heavy Gloves",
    image: "",
    description: "DEF + 20",
    gold: 50,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.GLOVES,
    armor: 20,
  },
  [EquipmentId.HEAVY_BOOTS]: {
    label: "Heavy Boots",
    image: "",
    description: "DEF + 20",
    gold: 55,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.BOOTS,
    armor: 20,
  },
  [EquipmentId.HEAVY_HELMET]: {
    label: "Heavy Helmet",
    image: "",
    description: "DEF + 20",
    gold: 60,
    status: BonusStatus.LOCKED,
    slot: EquipmentSlot.HELMET,
    armor: 20,
  },
};
