import { StatKey, ItemId } from "@/enums";
import type { Item } from "@/types";
import {
  healthPotion,
  bigHealthPotion,
  giantHealthPotion,
  energyPotion,
  bigEnergyPotion,
  giantEnergyPotion,
  strengthPotion,
  bigStrengthPotion,
  giantStrengthPotion,
  defensePotion,
  bigDefensePotion,
  giantDefensePotion,
} from "@/assets";

export const ITEMS: Record<ItemId, Item> = {
  [ItemId.HEALTH_POTION]: {
    label: "Health Potion",
    description: "Restores 20% of Max HP",
    image: healthPotion,
    gold: 100,
    amount: 0,
    stats: [StatKey.HEALTH],
    modifier: 0.2,
  },
  [ItemId.BIG_HEALTH_POTION]: {
    label: "Big Health Potion",
    description: "Restores 40% of Max HP",
    image: bigHealthPotion,
    gold: 200,
    amount: 0,
    stats: [StatKey.HEALTH],
    modifier: 0.4,
  },
  [ItemId.GIANT_HEALTH_POTION]: {
    label: "Giant Health Potion",
    description: "Restores 60% of Max HP",
    image: giantHealthPotion,
    gold: 300,
    amount: 0,
    stats: [StatKey.HEALTH],
    modifier: 0.6,
  },

  [ItemId.ENERGY_POTION]: {
    label: "Energy Potion",
    description: "Restores 20% of Max EP",
    image: energyPotion,
    gold: 100,
    amount: 0,
    stats: [StatKey.STAMINA],
    modifier: 0.2,
  },
  [ItemId.BIG_ENERGY_POTION]: {
    label: "Big Energy Potion",
    description: "Restores 40% of Max EP",
    image: bigEnergyPotion,
    gold: 200,
    amount: 0,
    stats: [StatKey.STAMINA],
    modifier: 0.4,
  },
  [ItemId.GIANT_ENERGY_POTION]: {
    label: "Giant Energy Potion",
    description: "Restores 60% of Max EP",
    image: giantEnergyPotion,
    gold: 300,
    amount: 0,
    stats: [StatKey.STAMINA],
    modifier: 0.6,
  },

  [ItemId.STRENGTH_POTION]: {
    label: "Strength Potion",
    description: "Restores 20% of Max STR",
    image: strengthPotion,
    gold: 100,
    amount: 0,
    stats: [StatKey.STRENGTH],
    modifier: 0.2,
  },
  [ItemId.BIG_STRENGTH_POTION]: {
    label: "Big Strength Potion",
    description: "Restores 40% of Max STR",
    image: bigStrengthPotion,
    gold: 200,
    amount: 0,
    stats: [StatKey.STRENGTH],
    modifier: 0.4,
  },
  [ItemId.GIANT_STRENGTH_POTION]: {
    label: "Giant Strength Potion",
    description: "Restores 60% of Max STR",
    image: giantStrengthPotion,
    gold: 300,
    amount: 0,
    stats: [StatKey.STRENGTH],
    modifier: 0.6,
  },

  [ItemId.DEFENSE_POTION]: {
    label: "Defense Potion",
    description: "Restores 20% of Max DEF",
    image: defensePotion,
    gold: 10,
    amount: 0,
    stats: [StatKey.DEFENSE],
    modifier: 0.2,
  },
  [ItemId.BIG_DEFENSE_POTION]: {
    label: "Big Defense Potion",
    description: "Restores 40% of Max DEF",
    image: bigDefensePotion,
    gold: 20,
    amount: 0,
    stats: [StatKey.DEFENSE],
    modifier: 0.4,
  },
  [ItemId.GIANT_DEFENSE_POTION]: {
    label: "Giant Defense Potion",
    description: "Restores 60% of Max DEF",
    image: giantDefensePotion,
    gold: 30,
    amount: 0,
    stats: [StatKey.DEFENSE],
    modifier: 0.6,
  },
};
