import { StatKey, ItemId } from "@/enums";
import type { Item } from "@/types";
import {
  healthPotion,
  bigHealthPotion,
  giantHealthPotion,
  grandHealthPotion,
  energyPotion,
  bigEnergyPotion,
  giantEnergyPotion,
  grandEnergyPotion,
  rejuvenationPotion,
  bigRejuvenationPotion,
  giantRejuvenationPotion,
  grandRejuvenationPotion,
  strengthPotion,
  bigStrengthPotion,
  giantStrengthPotion,
  grandStrengthPotion,
  defensePotion,
  bigDefensePotion,
  giantDefensePotion,
  grandDefensePotion,
  bonusHealthPotion,
  bonusEnergyPotion,
  bonusStrengthPotion,
  bonusDefensePotion,
} from "@/assets";

export const ITEMS: Record<ItemId, Item> = {
  [ItemId.HEALTH_POTION]: {
    label: "Health Potion",
    description: "Restores 20% of Max HP",
    image: healthPotion,
    gold: 10,
    amount: 0,
    stats: [StatKey.HEALTH],
    modifier: 0.2,
  },
  [ItemId.ENERGY_POTION]: {
    label: "Energy Potion",
    description: "Restores 20% of Max EP",
    image: energyPotion,
    gold: 10,
    amount: 0,
    stats: [StatKey.STAMINA],
    modifier: 0.2,
  },
  [ItemId.REJUVENATION_POTION]: {
    label: "Rejuvenation Potion",
    description: "Restores 10% of Max EP and HP",
    image: rejuvenationPotion,
    gold: 15,
    amount: 0,
    stats: [StatKey.HEALTH, StatKey.STAMINA],
    modifier: 0.1,
  },
  [ItemId.STRENGTH_POTION]: {
    label: "Strength Potion",
    description: "Restores 20% of Max STR",
    image: strengthPotion,
    gold: 10,
    amount: 0,
    stats: [StatKey.STRENGTH],
    modifier: 0.2,
  },
  [ItemId.DEFENSE_POTION]: {
    label: "Defense Potion",
    description: "Restores 20% of Max DEF",
    image: defensePotion,
    gold: 10,
    amount: 0,
    stats: [StatKey.DEFENSE],
    modifier: 0.2,
  },
  [ItemId.BIG_HEALTH_POTION]: {
    label: "Big Health Potion",
    description: "Restores 40% of Max HP",
    image: bigHealthPotion,
    gold: 20,
    amount: 0,
    stats: [StatKey.HEALTH],
    modifier: 0.4,
  },
  [ItemId.BIG_ENERGY_POTION]: {
    label: "Big Energy Potion",
    description: "Restores 40% of Max EP",
    image: bigEnergyPotion,
    gold: 20,
    amount: 0,
    stats: [StatKey.STAMINA],
    modifier: 0.4,
  },
  [ItemId.BIG_REJUVENATION_POTION]: {
    label: "Big Rejuvenation Potion",
    description: "Restores 20% of Max EP and HP",
    image: bigRejuvenationPotion,
    gold: 25,
    amount: 0,
    stats: [StatKey.HEALTH, StatKey.STAMINA],
    modifier: 0.2,
  },
  [ItemId.BIG_STRENGTH_POTION]: {
    label: "Big Strength Potion",
    description: "Restores 40% of Max STR",
    image: bigStrengthPotion,
    gold: 20,
    amount: 0,
    stats: [StatKey.STRENGTH],
    modifier: 0.4,
  },
  [ItemId.BIG_DEFENSE_POTION]: {
    label: "Big Defense Potion",
    description: "Restores 40% of Max DEF",
    image: bigDefensePotion,
    gold: 20,
    amount: 0,
    stats: [StatKey.DEFENSE],
    modifier: 0.4,
  },
  [ItemId.GIANT_HEALTH_POTION]: {
    label: "Giant Health Potion",
    description: "Restores 60% of Max HP",
    image: giantHealthPotion,
    gold: 30,
    amount: 0,
    stats: [StatKey.HEALTH],
    modifier: 0.6,
  },
  [ItemId.GIANT_ENERGY_POTION]: {
    label: "Giant Energy Potion",
    description: "Restores 60% of Max EP",
    image: giantEnergyPotion,
    gold: 30,
    amount: 0,
    stats: [StatKey.STAMINA],
    modifier: 0.6,
  },
  [ItemId.GIANT_REJUVENATION_POTION]: {
    label: "Giant Rejuvenation Potion",
    description: "Restores 30% of Max EP and HP",
    image: giantRejuvenationPotion,
    gold: 35,
    amount: 0,
    stats: [StatKey.HEALTH, StatKey.STAMINA],
    modifier: 0.3,
  },
  [ItemId.GIANT_STRENGTH_POTION]: {
    label: "Giant Strength Potion",
    description: "Restores 60% of Max STR",
    image: giantStrengthPotion,
    gold: 30,
    amount: 0,
    stats: [StatKey.STRENGTH],
    modifier: 0.6,
  },
  [ItemId.GIANT_DEFENSE_POTION]: {
    label: "Giant Defense Potion",
    description: "Restores 60% of Max DEF",
    image: giantDefensePotion,
    gold: 30,
    amount: 0,
    stats: [StatKey.DEFENSE],
    modifier: 0.6,
  },
  [ItemId.GRAND_HEALTH_POTION]: {
    label: "Grand Health Potion",
    description: "Restores 80% of Max HP",
    image: grandHealthPotion,
    gold: 40,
    amount: 0,
    stats: [StatKey.HEALTH],
    modifier: 0.8,
  },
  [ItemId.GRAND_ENERGY_POTION]: {
    label: "Grand Energy Potion",
    description: "Restores 80% of Max EP",
    image: grandEnergyPotion,
    gold: 40,
    amount: 0,
    stats: [StatKey.STAMINA],
    modifier: 0.8,
  },
  [ItemId.GRAND_REJUVENATION_POTION]: {
    label: "Grand Rejuvenation Potion",
    description: "Restores 40% of Max EP and HP",
    image: grandRejuvenationPotion,
    gold: 45,
    amount: 0,
    stats: [StatKey.HEALTH, StatKey.STAMINA],
    modifier: 0.4,
  },
  [ItemId.GRAND_STRENGTH_POTION]: {
    label: "Grand Strength Potion",
    description: "Restores 80% of Max STR",
    image: grandStrengthPotion,
    gold: 40,
    amount: 0,
    stats: [StatKey.STRENGTH],
    modifier: 0.8,
  },
  [ItemId.GRAND_DEFENSE_POTION]: {
    label: "Grand Defense Potion",
    description: "Restores 80% of Max DEF",
    image: grandDefensePotion,
    gold: 40,
    amount: 0,
    stats: [StatKey.DEFENSE],
    modifier: 0.8,
  },
  [ItemId.BONUS_HEALTH_POTION]: {
    label: "Bonus Health Potion",
    description: "Increases Max HP by 10",
    image: bonusHealthPotion,
    gold: 1000,
    amount: 0,
    stats: [StatKey.MAX_HEALTH],
    modifier: 10,
  },
  [ItemId.BONUS_ENERGY_POTION]: {
    label: "Bonus Energy Potion",
    description: "Increases Max EP by 10",
    image: bonusEnergyPotion,
    gold: 1000,
    amount: 0,
    stats: [StatKey.MAX_STAMINA],
    modifier: 10,
  },
  [ItemId.BONUS_STRENGTH_POTION]: {
    label: "Bonus Strength Potion",
    description: "Increases Max STR by 1",
    image: bonusStrengthPotion,
    gold: 1000,
    amount: 0,
    stats: [StatKey.MAX_STRENGTH],
    modifier: 1,
  },
  [ItemId.BONUS_DEFENSE_POTION]: {
    label: "Bonus Defense Potion",
    description: "Increases Max DEF by 1",
    image: bonusDefensePotion,
    gold: 1000,
    amount: 0,
    stats: [StatKey.MAX_DEFENSE],
    modifier: 1,
  },
};
