export const LABELS = {
  HEALTH: "HP",
  STAMINA: "SP",
  MANA: "MP",
  EXPERIENCE: "XP",
  STRENGTH: "STR",
  DEXTERITY: "DEX",
  DEFENSE: "DEF",
  GOLD: "GOLD",
  VITALITY: "VIT",
  ENDURANCE: "END",
  FIGHT: "Fight",
  TRAIN: "Train",
  REST: "Rest",
  STOP: "Stop",
  SHOW_STATS: "Stats",
  HIDE_STATS: "Back",
  CONTINUE: "Continue",
  LEVEL: "Lv",
  NEW_GAME: "New Game",
  LOAD_GAME: "Load Game",
};
