import { Label, Language } from "@/enums";

export const LABELS: Record<Language, Record<Label, string>> = {
  [Language.ENGLISH]: {
    [Label.COLOSSEUM_CHAMPIONS]: "Colosseum Champions",
    [Label.TUTORIAL]: "Tutorial",
    [Label.QUEST_FOR_GLORY]: "Quest for Glory",
    [Label.OPTIONS]: "Options",
    [Label.CONTINUE]: "Continue",
    [Label.LEVEL]: "Lv",
    [Label.STATS]: "STATS",
    [Label.ABILITIES]: "ABILITIES",
    [Label.PERKS]: "PERKS",
    [Label.EQUIPMENT]: "EQUIPMENT",
    [Label.ITEMS]: "ITEMS",
    [Label.LOCKED]: "Locked",
    [Label.UNEQUIPPED]: "Unequipped",
    [Label.EQUIPPED]: "Equipped",
    [Label.ACTIVE]: "Active",
    [Label.LCK]: "LCK",
    [Label.UNEQ]: "UNEQ",
    [Label.EQP]: "EQP",
    [Label.ACT]: "ACT",
    [Label.UNLOCK]: "Unlock",
    [Label.EQUIP]: "Equip",
    [Label.UNEQUIP]: "Unequip",
    [Label.ACTIVATE]: "Activate",
    [Label.DEACTIVATE]: "Deactivate",
  },
  [Language.GREEK]: {
    [Label.COLOSSEUM_CHAMPIONS]: "Πρωταθλητές του Κολοσσαίου",
    [Label.TUTORIAL]: "Εκπαίδευση",
    [Label.QUEST_FOR_GLORY]: "Αναζήτηση της Δόξας",
    [Label.OPTIONS]: "Επιλογές",
    [Label.CONTINUE]: "Συνέχισε",
    [Label.LEVEL]: "Επ",
    [Label.STATS]: "ΣΤΑΤΙΣΤΙΚΑ",
    [Label.ABILITIES]: "ΙΚΑΝΟΤΗΤΕΣ",
    [Label.PERKS]: "ΠΡΟΝΟΜΙΑ",
    [Label.EQUIPMENT]: "ΕΞΟΠΛΙΣΜΟΣ",
    [Label.ITEMS]: "ΑΝΤΙΚΕΙΜΕΝΑ",
    [Label.LOCKED]: "Κλειδωμένο",
    [Label.UNEQUIPPED]: "Μη Εξοπλισμένο",
    [Label.EQUIPPED]: "Εξοπλισμένο",
    [Label.ACTIVE]: "Ενεργό",
    [Label.LCK]: "ΚΛΔ",
    [Label.UNEQ]: "ΜΕΞΠ",
    [Label.EQP]: "ΕΞΠ",
    [Label.ACT]: "ΕΝΡ",
    [Label.UNLOCK]: "Ξεκλείδωσε",
    [Label.EQUIP]: "Εξοπλίσου",
    [Label.UNEQUIP]: "Αφαίρεσε",
    [Label.ACTIVATE]: "Ενεργοποίησε",
    [Label.DEACTIVATE]: "Απενεργοποίησε",
  },
};
