export const LABELS = {
  HEALTH: "HP",
  STAMINA: "SP",
  RAGE: "RP",
  EXPERIENCE: "XP",
  STRENGTH: "STR",
  DEXTERITY: "DEX",
  DEFENSE: "DEF",
  GOLD: "GOLD",
  VITALITY: "VIT",
  ENDURANCE: "END",
  FIGHT: "F",
  TRAIN: "T",
  REST: "R",
  STOP: "S",
  SHOW_STATS: "Stats",
  HIDE_STATS: "Back",
  CONTINUE: "Continue",
  LEVEL: "Lv",
  NEW_GAME: "New Game",
  LOAD_GAME: "Load Game",
  POINTS: "POINTS",
  CODEX: "C",
  ARMORY: "A",
  ITEMS: "I",
};
