import {
  background01,
  background02,
  background03,
  background04,
  background05,
  background06,
  background07,
  background08,
  background09,
  background10,
  background11,
  background12,
} from "@/assets";
import type { Stage } from "@/types";

export const STAGES: Stage[] = [
  {
    label: "Chapter 1",
    description: "Whispering Forest",
    image: background01,
    gold: 0,
    level: 1,
  },
  {
    label: "Chapter 2",
    description: "Forgotten Village",
    image: background02,
    gold: 10,
    level: 11,
  },
  {
    label: "Chapter 3",
    description: "Misty Marshlands",
    image: background03,
    gold: 20,
    level: 21,
  },
  {
    label: "Chapter 4",
    description: "Ancient Ruins",
    image: background04,
    gold: 30,
    level: 31,
  },
  {
    label: "Chapter 5",
    description: "Cavern of Echoes",
    image: background05,
    gold: 40,
    level: 41,
  },
  {
    label: "Chapter 6",
    description: "Haunted Crypt",
    image: background06,
    gold: 50,
    level: 51,
  },
  {
    label: "Chapter 7",
    description: "Sunken Temple",
    image: background07,
    gold: 60,
    level: 61,
  },
  {
    label: "Chapter 8",
    description: "Black Iron Mines",
    image: background08,
    gold: 70,
    level: 71,
  },
  {
    label: "Chapter 9",
    description: "Bloodfang Keep",
    image: background09,
    gold: 80,
    level: 81,
  },
  {
    label: "Chapter 10",
    description: "Infernal Chasm",
    image: background10,
    gold: 90,
    level: 91,
  },
  {
    label: "Chapter 11",
    description: "Sanctum of Shadows",
    image: background11,
    gold: 100,
    level: 101,
  },
  {
    label: "Chapter 12",
    description: "Crimson Castle",
    image: background12,
    gold: 110,
    level: 111,
  },
];
