import gameBackground from "@/assets/gameBackground.png";
import titleBackground from "@/assets/titleBackground.gif";
import dungeonBackground from "@/assets/dungeonBackground.jpg";
import logo from "@/assets/logo.png";

import {
  dagger1,
  dagger2,
  dagger3,
  dagger4,
  dagger5,
  sword1,
  sword2,
  sword3,
  sword4,
  sword5,
  axe1,
  axe2,
  axe3,
  axe4,
  axe5,
  mace1,
  mace2,
  mace3,
  mace4,
  mace5,
  spear1,
  spear2,
  spear3,
  spear4,
  spear5,
  shield1,
  shield2,
  shield3,
  shield4,
  shield5,
  shield6,
  shield7,
  shield8,
  shield9,
  shield10,
} from "@/assets/equipment";
import {
  healthPotion,
  bigHealthPotion,
  giantHealthPotion,
  grandHealthPotion,
  energyPotion,
  bigEnergyPotion,
  giantEnergyPotion,
  grandEnergyPotion,
  rejuvenationPotion,
  bigRejuvenationPotion,
  giantRejuvenationPotion,
  grandRejuvenationPotion,
  strengthPotion,
  bigStrengthPotion,
  giantStrengthPotion,
  grandStrengthPotion,
  defensePotion,
  bigDefensePotion,
  giantDefensePotion,
  grandDefensePotion,
  bonusHealthPotion,
  bonusEnergyPotion,
  bonusStrengthPotion,
  bonusDefensePotion,
  bonusPointsPotion,
} from "@/assets/items";
import { smash } from "@/assets/abilities";
import { defensive } from "@/assets/perks";
import {
  enemy1Death,
  enemy1Idle,
  enemy1Attack,
  enemy1Hurt,
} from "@/assets/enemies";
import { scene1, scene2 } from "@/assets/cutscenes";
import {
  perks,
  items,
  abilities,
  gold,
  equipment,
  arena,
  points,
  experience,
  defense,
  strength,
  health,
  energy,
} from "@/assets/ui";

export {
  gameBackground,
  titleBackground,
  logo,
  dungeonBackground,
  dagger1,
  dagger2,
  dagger3,
  dagger4,
  dagger5,
  sword1,
  sword2,
  sword3,
  sword4,
  sword5,
  axe1,
  axe2,
  axe3,
  axe4,
  axe5,
  mace1,
  mace2,
  mace3,
  mace4,
  mace5,
  spear1,
  spear2,
  spear3,
  spear4,
  spear5,
  shield1,
  shield2,
  shield3,
  shield4,
  shield5,
  shield6,
  shield7,
  shield8,
  shield9,
  shield10,
  healthPotion,
  bigHealthPotion,
  giantHealthPotion,
  grandHealthPotion,
  energyPotion,
  bigEnergyPotion,
  giantEnergyPotion,
  grandEnergyPotion,
  rejuvenationPotion,
  bigRejuvenationPotion,
  giantRejuvenationPotion,
  grandRejuvenationPotion,
  strengthPotion,
  bigStrengthPotion,
  giantStrengthPotion,
  grandStrengthPotion,
  defensePotion,
  bigDefensePotion,
  giantDefensePotion,
  grandDefensePotion,
  bonusHealthPotion,
  bonusEnergyPotion,
  bonusStrengthPotion,
  bonusDefensePotion,
  bonusPointsPotion,
  smash,
  defensive,
  enemy1Death,
  enemy1Idle,
  enemy1Attack,
  enemy1Hurt,
  scene1,
  scene2,
  perks,
  items,
  abilities,
  gold,
  equipment,
  arena,
  points,
  experience,
  defense,
  strength,
  health,
  energy,
};
